language: go

go:
  - 1.2
  - 1.3
  - tip

before_install:
  - sudo apt-get install -q -y supervisor

install:
  - go get gopkg.in/mgo.v2/bson
  - go get gopkg.in/check.v1

before_script:
  - pwd
  - ls -lart
  - mkdir -p ~/gopath/src/gopkg.in/mgo.v2
  - cp -r ./mgoscratch/* ~/gopath/src/gopkg.in/mgo.v2
  - make startdb

script: 
  - cd ~/gopath/src/gopkg.in/mgo.v2
  - go test -gocheck.v

after_script:
  - make stopdb

notifications:
  email: false
